/*
   +----------------------------------------------------------------------+
   | PHP Nano                                                            |
   +----------------------------------------------------------------------+
   | Static Composer extension ABI.                                      |
   | SPDX-License-Identifier: BSD-3-Clause                               |
   +----------------------------------------------------------------------+
*/

#ifndef PHP_NANO_EXTENSION_H
#define PHP_NANO_EXTENSION_H

#include "php.h"
#include <zend_modules.h>
#include <stdint.h>

#ifndef PHP_NANO_API
#define PHP_NANO_API PHPAPI
#endif

BEGIN_EXTERN_C()

PHP_NANO_API zend_result php_nano_startup_core(void);
PHP_NANO_API zend_result php_nano_activate_core(void);
PHP_NANO_API void php_nano_deactivate_core(void);
PHP_NANO_API void php_nano_shutdown_core(void);
PHP_NANO_API void php_nano_set_cli_arguments(int argc, char **argv);
PHP_NANO_API zend_result php_nano_startup_extensions(
    zend_module_entry *const *extensions, size_t count);
PHP_NANO_API void php_nano_shutdown_extensions(void);
PHP_NANO_API zend_module_entry *php_nano_find_extension(const char *name);
PHP_NANO_API int64_t php_nano_system_time_seconds(void);
PHP_NANO_API void php_nano_system_time(int64_t *seconds, int32_t *microseconds);
PHP_NANO_API zend_string *php_nano_unique_id(zend_string *prefix, bool more_entropy);
PHP_NANO_API zend_result php_nano_random_bytes(void *bytes, size_t size);
PHP_NANO_API uint64_t php_nano_random_seed(void);
#ifdef PHP_NANO_NO_LIBC
/* Freestanding embedders supply entropy without pulling in a hosted C++
 * runtime. The provider may return FAILURE when no entropy source exists. */
PHP_NANO_API zend_result php_nano_host_random_bytes(void *bytes, size_t size);
PHP_NANO_API uint64_t php_nano_host_random_seed(void);
PHP_NANO_API void php_nano_host_system_time(int64_t *seconds, int32_t *microseconds);
PHP_NANO_API uint64_t php_nano_host_monotonic_nanoseconds(void);
PHP_NANO_API void php_nano_host_sleep(uint64_t seconds, uint32_t nanoseconds);
#endif
PHP_NANO_API zend_result php_nano_startup_bcmath(void);
PHP_NANO_API void php_nano_shutdown_bcmath(void);

/* Implemented by the registry source generated by TypePHP. */
PHP_NANO_API zend_result php_nano_startup_composer_extensions(void);
PHP_NANO_API void php_nano_shutdown_composer_extensions(void);

END_EXTERN_C()

#endif
